### ISSUE TITLE
[BUG] 로그인 스크린 스케일 조정

### ISSUE THREAD

**Issue by Soju06** [masang1/majang.frontend#13]
## 🤷 버그 내용
![image](https://github.com/masang1/majang.frontend/assets/34199905/7c8572fa-f54e-4fd7-84c4-e95e8900c3e7)

- [ ] 위 "마법의 장터" 글귀 bold로 변경
- [ ] 메인 로고 크기 조금 더 작게
- [ ] 로그인 버튼 아래 디자인 참고하여 primary 색상과 bold로 변경

![image](https://github.com/masang1/majang.frontend/assets/34199905/e43fc4ad-1656-49f2-97b3-aeddb73469ba)

**Comment by choi138** [comment]
박찬영이 완료했습니다
