### ISSUE TITLE
[BUG] 약관 동의 - 모두 동의 Checkbox 스케일 조정

### ISSUE THREAD

**Issue by Soju06** [masang1/majang.frontend#23]
## 🤷 버그 내용
아래 사진과 같이 '모두 동의' checkbox와 하단 약관 checkbox의 크기가 맞지 않습니다.
모두 동의 checkbox를 약관 checkbox 크기와 맞춰주세요.

또는 checkbox를 가운데 정렬하는 방법도 있겠네요.

![image](https://github.com/masang1/majang.frontend/assets/34199905/c1f3faf5-1480-45c0-8864-a263cdf2db76)

**Comment by pcy06** [comment]
추가로, "모두 동의" 버튼이 필수 동의사항만 체크해도 활성화됩니다

**Comment by choi138** [comment]
bug/16 브랜치에서 수정했습니다~
