### ISSUE TITLE
[FEATURE] 전화번호 입력란 디자인 변경

### ISSUE THREAD

**Issue by Soju06** [masang1/majang.frontend#34]
## 💣 기능 설명
![image](https://github.com/masang1/majang.frontend/assets/34199905/aca07665-03c6-4bd0-8beb-f5a751dae21b)
위 사진처럼 전화번호 작성중에도 빨간색 오류 메시지가 나오니 디자인적으로 별로입니다.
계속버튼 활성화 여부로만 전화번호 validate해주세요.

**Comment by choi138** [comment]
버튼 활성화 여부로만 하게되면 일반 사용자가 당황스러울 수 있기 때문에 버튼을 누른후에 에러 메세지를 띄우게끔 수정 했습니다
