### ISSUE TITLE
[FEATURE] 애플리케이션 로딩로고 크기 조정

### ISSUE THREAD

**Issue by Soju06** [masang1/majang.frontend#35]
## 💣 기능 설명
![image](https://github.com/masang1/majang.frontend/assets/34199905/a4ed9eb1-2655-42a1-bcb2-c35d7353d1fa)
위 사진처럼 애플리케이션 로딩로고가 너무 큽니다.
랜딩 페이지 로고보다 조금 더 크게 설정해주세요.

**Comment by choi138** [comment]
수정했습니다
